# Generated by Django 6.0.3 on 2026-04-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(blank=True, max_length=100)),
                ('beneficiario', models.CharField(blank=True, max_length=200)),
                ('credor', models.CharField(blank=True, max_length=200)),
                ('natureza', models.CharField(blank=True, max_length=20)),
                ('ano_orcamento', models.IntegerField(blank=True, null=True)),
                ('tipo_calculo', models.CharField(blank=True, max_length=20)),
                ('data_atualizacao', models.DateField(blank=True, null=True)),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_juros', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_selic', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_ir', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_previdencia', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_honorarios', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tem_herdeiros', models.BooleanField(default=False)),
                ('tem_honorario_sucumbencial', models.BooleanField(default=False)),
                ('tem_pagamentos', models.BooleanField(default=False)),
                ('dados_entrada', models.JSONField()),
                ('resultado_completo', models.JSONField()),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
                'ordering': ['-data_calculo'],
            },
        ),
    ]
