# Generated by Django 6.0.3 on 2026-04-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo',
            name='valor_honorarios',
        ),
        migrations.RemoveField(
            model_name='calculo',
            name='valor_ir',
        ),
        migrations.RemoveField(
            model_name='calculo',
            name='valor_liquido',
        ),
        migrations.RemoveField(
            model_name='calculo',
            name='valor_previdencia',
        ),
        migrations.AddField(
            model_name='calculo',
            name='hist_juros',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='hist_principal',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='hist_selic',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='hist_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='rra',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='CalculoCredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('beneficiario', 'Beneficiário'), ('herdeiro', 'Herdeiro'), ('advogado', 'Advogado Contratual'), ('advogado_suc', 'Advogado Sucumbencial'), ('sindicato', 'Sindicato'), ('cessionario_ben', 'Cessionário do Beneficiário'), ('cessionario_adv', 'Cessionário de Advogado'), ('cessionario_adv_suc', 'Cessionário de Adv. Sucumbencial'), ('cessionario_sind', 'Cessionário de Sindicato'), ('cessionario_herd', 'Cessionário de Herdeiro')], max_length=30)),
                ('cedente', models.CharField(blank=True, max_length=200)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_previdencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_ir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credores', to='core.calculo')),
            ],
            options={
                'verbose_name': 'Credor',
                'verbose_name_plural': 'Credores',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
