# Generated by Django 6.0.3 on 2026-04-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_calculo_valor_honorarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='data_base',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='indice_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
