# Generated by Django 6.0.3 on 2026-04-09 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calculo_data_base_calculo_indice_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bug', 'Bug / Erro'), ('melhoria', 'Sugestão de Melhoria'), ('duvida', 'Dúvida')], max_length=20)),
                ('descricao', models.TextField()),
                ('numero_processo', models.CharField(blank=True, max_length=100)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calculo')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-data_envio'],
            },
        ),
    ]
