# Generated by Django 6.0.3 on 2026-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
