# Generated by Django 6.0.3 on 2026-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback_nome_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('beneficiario', models.CharField(blank=True, max_length=200)),
                ('credor', models.CharField(blank=True, max_length=200)),
                ('natureza', models.CharField(blank=True, max_length=20)),
                ('ano_orcamento', models.IntegerField(blank=True, null=True)),
                ('data_base', models.DateField(blank=True, null=True)),
                ('valor_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='IndiceMonetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ipca', 'IPCA'), ('ipca_e', 'IPCA-E'), ('selic', 'SELIC'), ('cnj', 'CNJ/JE'), ('poupanca', 'Poupança')], max_length=10)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
            options={
                'verbose_name': 'Índice Monetário',
                'verbose_name_plural': 'Índices Monetários',
                'ordering': ['tipo', 'ano', 'mes'],
                'unique_together': {('tipo', 'ano', 'mes')},
            },
        ),
    ]
