# Generated by Django 6.0.3 on 2026-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_processo_indicemonetario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicemonetario',
            name='tipo',
            field=models.CharField(choices=[('ipca', 'IPCA'), ('ipca_e', 'IPCA-E'), ('selic', 'SELIC'), ('cnj', 'CNJ/JE'), ('juros_mora_alimentar', 'Juros de Mora Alimentar'), ('juros_mora_comum', 'Juros de Mora Comum')], max_length=25),
        ),
    ]
